#travis configuration for coverage testing of jado
# M A Chatterjee 2020-12-23

language: node_js
node_js:
  - "14"
#dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch Chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
  chrome: stable # have Travis install Chrome stable.
cache: npm
script:
  - npm run test

#
#before_install:
#  - npm install coveralls
#
#after_success: npm run coveralls
#
#branches:
#  only:
#    - master